version: '3.8'

services:
  # [2] 백엔드 서비스
  trip-backend:
    image: junho010712/trip-backend:latest
    container_name: trip-backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/trip_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1771
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - goorm-trip-net

  # [3] 프론트엔드 메인 (3000)
  trip-main:
    image: junho010712/trip-front:latest
    container_name: trip-main-container
    ports:
      - "3000:80"
    environment:
      - VITE_SERVICE_NAME=MAIN_PORTAL
    networks:
      - goorm-trip-net

  # [4] 프론트엔드 장바구니 (3001)
  trip-cart:
    image: junho010712/trip-front:latest
    container_name: trip-cart-container
    ports:
      - "3001:80"
    environment:
      - VITE_SERVICE_NAME=CART_SERVICE
    networks:
      - goorm-trip-net

  # [5] 프론트엔드 결제 (3002)
  trip-payment:
    image: junho010712/trip-front:latest
    container_name: trip-payment-container
    ports:
      - "3002:80"
    environment:
      - VITE_SERVICE_NAME=PAYMENT_SERVICE
    networks:
      - goorm-trip-net

networks:
  goorm-trip-net:
    driver: bridge